{% set name = "TauDEM" %}
{% set version = "5.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dtarb/TauDEM/archive/v{{ version }}.tar.gz
  sha256: 30aee134f5eed2fb65825dd4e9e5181ed4ea6ae22c37d56ae5cfe2bdb9dab385

build:
  number: 2
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make  # [linux]
    - cmake  # [linux]
  host:
    - libgdal
    - mpich  # [linux]
    - msmpi  # [win]
  run:
    - libgdal
    - mpich  # [linux]
    - msmpi  # [win]

test:
  commands:
    - test -f $PREFIX/bin/d8flowdir  # [linux]
    - if not exist %LIBRARY_BIN%\\D8FlowDir.exe exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\D8FlowDir.lib exit 1  # [win]

about:
  home: http://hydrology.usu.edu/taudem
  license: GPL-3.0-only
  license_file: license.txt
  summary: Terrain Analysis Using Digital Elevation Models (TauDEM)
  description: TauDEM is a suite of Digital Elevation Model (DEM) tools for the extraction and analysis of hydrologic information from topography as represented by a DEM.
  doc_url: https://hydrology.usu.edu/taudem/taudem5/documentation.html
  dev_url: https://github.com/dtarb/TauDEM

extra:
  recipe-maintainers:
    - RyanMcCarthy-NOAA
